package com.example.uaep.uitmp
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFf38f48)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdbc4)
val md_theme_light_onPrimaryContainer = Color(0xFF321300)
val md_theme_light_secondary = Color(0xFF2a5bf0)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdce1ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001258)
val md_theme_light_tertiary = Color(0xFF616134)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFe6e5ad)
val md_theme_light_onTertiaryContainer = Color(0xFF1d1d00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a17)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a17)
val md_theme_light_surfaceVariant = Color(0xFFf4ded3)
val md_theme_light_onSurfaceVariant = Color(0xFF52443c)
val md_theme_light_outline = Color(0xFF85746b)
val md_theme_light_inverseOnSurface = Color(0xFFfaeee8)
val md_theme_light_inverseSurface = Color(0xFF362f2b)
val md_theme_light_inversePrimary = Color(0xFFffb685)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFffb685)
val md_theme_dark_onPrimary = Color(0xFF522300)
val md_theme_dark_primaryContainer = Color(0xFF743500)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdbc4)
val md_theme_dark_secondary = Color(0xFFb7c4ff)
val md_theme_dark_onSecondary = Color(0xFF00238a)
val md_theme_dark_secondaryContainer = Color(0xFF0034c0)
val md_theme_dark_onSecondaryContainer = Color(0xFFdce1ff)
val md_theme_dark_tertiary = Color(0xFFcac993)
val md_theme_dark_onTertiary = Color(0xFF32320a)
val md_theme_dark_tertiaryContainer = Color(0xFF49491f)
val md_theme_dark_onTertiaryContainer = Color(0xFFe6e5ad)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a17)
val md_theme_dark_onBackground = Color(0xFFece0da)
val md_theme_dark_surface = Color(0xFF201a17)
val md_theme_dark_onSurface = Color(0xFFece0da)
val md_theme_dark_surfaceVariant = Color(0xFF52443c)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c2b7)
val md_theme_dark_outline = Color(0xFF9f8d83)
val md_theme_dark_inverseOnSurface = Color(0xFF201a17)
val md_theme_dark_inverseSurface = Color(0xFFece0da)
val md_theme_dark_inversePrimary = Color(0xFF974800)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFf38f48)
val error = Color(0xFFba1b1b)